#!/usr/bin/env python3
"""colour_extract_presets.py <oracle> [out.inc] — extract ncde_presets::kPresets (the 90 Iris Chroma
palettes: id|name|dark|accent|border|panelBg|surface|ink|inkSoft, 9 x 8-byte slots per entry) from the
oracle LaPivot. The oracle holds THREE copies (one per function that used the header's static table);
all three must be identical or this refuses. Pointers are PIE R_X86_64_RELATIVE addends; vaddr == file
offset. Writes src/NCDEEngine_presets.inc (the rebuilt source's single copy). Without out: prints JSON."""
import json, subprocess, sys
SRC = sys.argv[1]
data = open(SRC, "rb").read()
relocs = {}
for line in subprocess.run(["readelf", "-rW", SRC], capture_output=True, text=True).stdout.splitlines():
    p = line.split()
    if len(p) >= 4 and p[2] == "R_X86_64_RELATIVE":
        relocs[int(p[0], 16)] = int(p[3], 16)
tables = sorted(int(l.split()[0], 16) for l in subprocess.run(["nm", SRC], capture_output=True, text=True).stdout.splitlines()
                if l.endswith("_ZN12ncde_presetsL8kPresetsE"))
assert len(tables) == 3, tables
def cstr(off):
    return data[off:data.index(b"\0", off)].decode()
def table(base):
    out = []
    for e in range(90):
        b = base + e * 72
        row = {}
        for fi, k in enumerate(["id", "name", "dark", "accent", "border", "panelBg", "surface", "ink", "inkSoft"]):
            if k == "dark":
                row[k] = data[b + 16] != 0
            else:
                row[k] = cstr(relocs[b + fi * 8])
        out.append(row)
    return out
t = [table(b) for b in tables]
if not (t[0] == t[1] == t[2]):
    sys.exit("REFUSE: the three kPresets copies differ")
if len(sys.argv) < 3:
    print(json.dumps(t[0], indent=1)); sys.exit(0)
with open(sys.argv[2], "w") as f:
    f.write("// GENERATED by tests/colour_extract_presets.py from the oracle LaPivot (all 3 kPresets copies identical).\n"
            "// The 90 Iris Chroma palettes (operator-curated; Filigree phase 1: 'hardcoded for a reason').\n"
            "// Fields: id, name, dark, accent, border, panelBg, surface, ink, inkSoft\n")
    for r in t[0]:
        f.write('{ %s, %s, %s, "%s", "%s", "%s", "%s", "%s", "%s" },\n' % (
            json.dumps(r["id"], ensure_ascii=False), json.dumps(r["name"], ensure_ascii=False),
            "true" if r["dark"] else "false", r["accent"], r["border"], r["panelBg"], r["surface"], r["ink"], r["inkSoft"]))
print("kPresets: 90 entries, 3 identical copies")
